package wui.bridge;

/**
	The entry point WinUI calls to start the Haxe runtime.

	`wui` used to be a pure transpiler: the generated project linked no hxcpp, so
	no Haxe ran in a built app. It does now — this class is what boots it, and
	what native code calls back into.

	## How the boot works

	WinUI owns the entry point (`wWinMain`, via `App`), so Haxe cannot own `main`.
	The pattern is the one both sibling backends already use:

	- **`qui`**: Qt owns `main` and calls `hx::Init()` *after* the view exists.
	- **`sui`**: Swift owns `@main` and calls `haxe_bridge_init` through `dlsym`,
	  so the runtime stays optional and detected.

	Here, `App::OnLaunched` calls `wui_bridge_init()` before building the window.
	The call is emitted by the generator, so an app gets it without asking.

	## The two mains

	hxcpp emits a `__main__` translation unit whose `main()` would clash with the
	one WinUI provides. Building with **`-D static_link`** replaces it with
	`__lib__`, which exposes `__hxcpp_lib_main()` and declares no `main` at all —
	hxcpp's own answer to being embedded, and it runs `lib.exe` itself to produce
	the static library.

	## Status

	**W1 through W5 done, all verified on Windows by clicking.** MSVC links the
	hxcpp library, `OnLaunched` boots it, buttons run real closures, Haxe state
	drives the controls both ways, and the acceptance app — the to-do list the
	design note called structurally impossible — runs.

	This class is the whole crossing:

	| Direction | Entry point |
	|---|---|
	| boot | `wui_bridge_init` |
	| C++ -> Haxe, a click | `wui_bridge_invoke` / `wui_bridge_invoke_row` |
	| C++ -> Haxe, a keystroke | `wui_bridge_external_string` (no echo back) |
	| Haxe -> C++, state | `wui_bridge_push_int` / `wui_bridge_push_string` |
	| Haxe -> C++, list rows | `wui_bridge_push_list` |

	**Known limits.** Only `Int` and `String` states reach the controls; other
	types are reported, not silently dropped. A list row is read as one text and
	at most one button — enough for a to-do list, and not a general `ForEach`.
	The general answer is the `nui` push contract, which is its own chantier.
	See `wui-hxcpp.md` in the atelier repo.
**/
#if cpp
@:cppFileCode('
#include <hxcpp.h>

// Generated by hxcpp into __lib__.cpp when compiling with -D static_link.
// It sets the stack top, runs hx::Boot() and then __boot_all(), which is what
// actually initialises every Haxe class. hx::Init() alone starts the runtime
// but boots nothing, so the first call into Haxe would find empty statics.
extern "C" void __hxcpp_lib_main();

static bool s_wui_haxe_started = false;

// Called by App::OnLaunched before the window is built.
//
// Idempotent: WinUI can raise OnLaunched more than once (relaunch, activation),
// and booting the runtime twice would be fatal.
extern "C" void wui_bridge_init() {
    if (s_wui_haxe_started) return;
    s_wui_haxe_started = true;
    __hxcpp_lib_main();

    // Cross back into Haxe immediately. Booting proves the library linked;
    // only a call landing in Haxe code proves the runtime is usable, so W1
    // is not done until this line reports for itself.
    ::wui::bridge::HaxeBridge_obj::hello();
}

// Whether the runtime is up. Lets generated code degrade rather than crash if
// the library was not linked in.
extern "C" bool wui_bridge_ready() {
    return s_wui_haxe_started;
}

// Build the Haxe view tree once and collect its closures into the registry.
//
// The class name is passed as a string because the generator writes App.cpp and
// already knows it -- which saves defining a Haxe type from the macro just to
// carry one identifier.
extern "C" int wui_bridge_install(const char* appClass) {
    if (!s_wui_haxe_started) return 0;
    return ::wui::bridge::HaxeBridge_obj::install(::String(appClass));
}

// Run the Haxe closure registered under `id`. Called from a Click handler, on
// the UI thread.
extern "C" void wui_bridge_invoke(int id) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invoke(id);
}

// ---- Haxe state -> generated C++ ----
//
// A slot, not a symbol resolved at link time. The generated MainWindow.cpp owns
// `s_<name>` and `notify_<name>()`, so it registers a handler here at startup and
// this library never names it. That keeps the hxcpp library linkable on its own:
// a test binary links it with no handler and pushes nowhere, which is how `sui`
// keeps its runtime optional and detected.
typedef void (*wui_int_handler)(const char*, int);
static wui_int_handler s_wui_int_handler = nullptr;

extern "C" void wui_bridge_set_int_handler(wui_int_handler fn) {
    s_wui_int_handler = fn;
}

// Called from Haxe when a state changes. Getting onto the UI thread is the
// handler\'s business -- it is the side that knows about the dispatcher.
extern "C" void wui_bridge_push_int(const char* name, int value) {
    if (s_wui_int_handler) s_wui_int_handler(name, value);
}

// Same slot, for text. Strings cross as UTF-8; the handler widens them.
typedef void (*wui_string_handler)(const char*, const char*);
static wui_string_handler s_wui_string_handler = nullptr;

extern "C" void wui_bridge_set_string_handler(wui_string_handler fn) {
    s_wui_string_handler = fn;
}

extern "C" void wui_bridge_push_string(const char* name, const char* value) {
    if (s_wui_string_handler) s_wui_string_handler(name, value);
}

// ---- the other direction: the user typed something ----
//
// A TextBox edit originates on the platform, so it must reach Haxe *without*
// being pushed straight back -- that echo would fight the caret on every
// keystroke. `rui.state.State.applyExternal` exists for exactly this: it runs
// the effects and skips the platform sink.
extern "C" void wui_bridge_external_string(const char* name, const char* value) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::applyExternalString(::String(name), ::String(value));
}

// ---- list rows ----
//
// The rows arrive as one flat payload: records separated by 0x1e, fields within
// a record by 0x1f. ASCII has had those two separators since before anyone
// needed a JSON parser, and a button label cannot contain them.
typedef void (*wui_list_handler)(const char*, const char*);
static wui_list_handler s_wui_list_handler = nullptr;

extern "C" void wui_bridge_set_list_handler(wui_list_handler fn) {
    s_wui_list_handler = fn;
}

extern "C" void wui_bridge_push_list(const char* name, const char* payload) {
    if (s_wui_list_handler) s_wui_list_handler(name, payload);
}

// Called at the end of BuildUI, once the ListViews exist and the handler is
// registered. Without it, rows present before the window was built are lost.
extern "C" void wui_bridge_refresh_lists() {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::refreshLists();
}

// Advance the Haxe-side scheduled work. Driven by a 100ms DispatcherQueueTimer
// in MainWindow.cpp -- the one periodic visit Haxe gets, since WinUI owns the
// message loop and the Haxe entry point that would pump after main() never
// runs here. Without it a haxe.Timer an application creates never fires.
extern "C" void wui_bridge_pump() {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::pumpHaxeEvents();
}

// A visit as soon as work is queued, not at the next beat. The host installs
// how to post one (MainWindow.cpp, from BuildUI, on the UI thread); installing
// it starts the watcher of the library on the event loop of that thread. A slot, so the
// library stays linkable without the generated window.
typedef void (*wui_pump_requester)();
static wui_pump_requester s_wui_pump_requester = nullptr;

extern "C" void wui_bridge_set_pump_requester(wui_pump_requester fn) {
    s_wui_pump_requester = fn;
    if (fn && s_wui_haxe_started) ::wui::bridge::HaxeBridge_obj::watchMainEvents();
}

// Called from the watcher thread; the requester only posts to the dispatcher.
static void wui_bridge_request_pump() {
    if (s_wui_pump_requester) s_wui_pump_requester();
}

// Mount the Haxe node tree into the root BuildUI just registered. The handle
// arrives as a parameter: it used to be a literal 0 hardwired on both sides,
// which held exactly as long as there was one window to be the zeroth.
extern "C" void wui_bridge_render_nui(int rootHandle) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::renderNui(rootHandle);
}

// Tear every surface down: the auxiliaries first (each releases its own
// lifetime), then the Primary, whose lifetime is the application\'s. The name
// kept its Primary-era spelling because the ABI list for the Windows pass
// already carries it; what it means is "the application is over".
extern "C" void wui_bridge_dispose_primary() {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::disposePrimary();
}

// ---- auxiliary windows ----
//
// A slot again, not a symbol: creating a winrt Window is the generated
// project\'s business, and naming its function here would make this library
// unlinkable on its own -- the same reasoning as the push handlers above.
// BuildUI registers the creator; a test injects a counting one on the Haxe
// side and this slot is never consulted.
typedef int (*wui_window_creator)(const char*);
static wui_window_creator s_wui_window_creator = nullptr;

extern "C" void wui_bridge_set_window_creator(wui_window_creator fn) {
    s_wui_window_creator = fn;
}

// Called from Haxe to open one auxiliary window. Returns the registered root
// handle, or -1 when no creator is installed (a build with no windows).
extern "C" int wui_bridge_create_window(const char* title) {
    return s_wui_window_creator ? s_wui_window_creator(title) : -1;
}

// An auxiliary window was closed by the user. The Haxe side disposes exactly
// that surface\'s record -- its effect and its own lifetime -- and nothing
// else; the controls die with their window and their handles become holes.
extern "C" void wui_bridge_surface_closed(int rootHandle) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::HaxeBridge_obj::surfaceClosed(rootHandle);
}

// A node property handler, from the nui push contract. A third entry point for
// a third id range -- see Callbacks.
extern "C" void wui_bridge_invoke_node(int id) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeNode(id);
}

// The same range, for a control that reports a value along with the event.
//
// This is the half of the push contract that makes a control two-way. Without
// it the sink could put a value on screen but never hear one back: a switch the
// user flipped changed nothing in Haxe, and the line reading the cell it was
// bound to never moved. The control is the authority on its own value at the
// moment it fires, so that value crosses with the event rather than being
// assumed from whatever Haxe last wrote.
extern "C" void wui_bridge_invoke_node_string(int id, const char* value) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeNodeString(id, ::String(value));
}

extern "C" void wui_bridge_invoke_node_float(int id, double value) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeNodeFloat(id, value);
}

extern "C" void wui_bridge_invoke_node_int(int id, int value) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeNodeInt(id, value);
}

extern "C" void wui_bridge_invoke_node_bool(int id, bool value) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeNodeBool(id, value);
}

// A row button. Separate from wui_bridge_invoke because row ids are rebuilt on
// every list change while the other table is fixed at compile time -- one entry
// point for each keeps a stale row click from running an unrelated closure.
extern "C" void wui_bridge_invoke_row(int id) {
    if (!s_wui_haxe_started) return;
    ::wui::bridge::Callbacks_obj::invokeRow(id);
}
')
#end
@:keep
class HaxeBridge {
	/**
		Proof of life, called from Haxe once the runtime is up.

		W1 succeeds when this line appears in the debug output of a running WinUI
		app — it means MSVC linked the hxcpp library, WinUI called into it, and
		Haxe executed. Nothing else about the app changes yet.
	**/
	public static function hello():Void {
		trace("[wui] Haxe runtime started");
	}

	/**
		Build the app's view tree in Haxe and register the closures it carries.

		The generated C++ builds the *controls*; this builds the same tree on the
		Haxe side purely to reach the closures, which exist nowhere else. `body()`
		is compiled like any other method even though the generated app never
		calls it — the macro reads it at compile time, and here we run it.

		Returns how many closures were found, so the caller can tell an app with
		no Haxe actions from a walk that went wrong.
	**/
	public static function install(appClass:String):Int {
		Callbacks.reset();

		var cls = Type.resolveClass(appClass);
		if (cls == null) {
			trace('[wui] install: class $appClass not found');
			return 0;
		}

		var app:Dynamic = Type.createInstance(cls, []);
		if (app == null) {
			trace('[wui] install: could not instantiate $appClass');
			return 0;
		}
		appInstance = app;

		var root:View = app.body();
		if (root == null) {
			trace('[wui] install: $appClass.body() returned null');
			return 0;
		}

		collect(root);
		bindLists(root);
		bindStates();
		return Callbacks.count();
	}

	/** The app built by `install()`. `renderNui` mounts from this same object. **/
	static var appInstance:Dynamic = null;

	/** Every `ListView` found in the tree, with the state that feeds it. **/
	static var lists:Array<{stateName:String, state:Dynamic, template:Dynamic}> = [];

	/**
		Find the lists and make them rebuild when their state changes.

		A list is the one place the generator cannot pre-emit: it does not know
		how many rows there will be. So Haxe keeps the item template, runs it on
		each element, and pushes the resulting rows across — the generated C++
		empties its `ListView` and refills it.

		**This is not a general `ForEach`.** A row is read as *one text and at
		most one button*, which is what a to-do list needs and no more. The
		general answer is the `nui` push contract, where Haxe holds the tree and
		patches native nodes; that is its own piece of work, not this one.
	**/
	static function bindLists(root:View):Void {
		lists = [];
		findLists(root);

		for (entry in lists) {
			var st:Dynamic = entry.state;
			st.subscribe(function(_) rebuildList(entry));
			rebuildList(entry);
		}
	}

	/**
		Push every list again.

		Called from the end of `BuildUI`. `install()` runs first — before the
		window exists — so the rebuild it does lands on a ListView that is still
		null, with no handler registered yet. An app whose list starts empty never
		notices; one with initial rows would show none of them, and only the first
		Add would make the list appear.
	**/
	public static function refreshLists():Void {
		for (entry in lists) rebuildList(entry);
	}

	static function findLists(view:View):Void {
		if (view == null) return;

		if (view.viewType == "ListView") {
			var items:Dynamic = view.properties.get("items");
			var template:Dynamic = view.properties.get("itemTemplate");

			if (items != null && Reflect.isFunction(template)) {
				// Typed access, not `items.name`: `name` is a `(get, never)`
				// property, and reading one through Dynamic does not call its
				// getter on hxcpp -- it fails, the way `.value` does. The cast
				// costs nothing and makes the getter run.
				var bound:rui.state.State<Dynamic> = cast items;
				var name:String = bound == null ? null : bound.name;

				if (name != null) {
					lists.push({stateName: name, state: items, template: template});
				} else {
					trace("[wui] a ListView is bound to something that is not a named State");
				}
			}
		}

		for (child in view.children) findLists(child);
	}

	/**
		Run the template over the current items and hand the rows to native code.

		Row callbacks are re-registered from scratch here, which is why they live
		in their own numbering — see `Callbacks`.
	**/
	static function rebuildList(entry:{stateName:String, state:Dynamic, template:Dynamic}):Void {
		Callbacks.resetRows();

		// Any iterable collection, not only Array. A list state is meant to hold
		// an ImmutableList -- whose `push` returns a new list, so a change is a
		// new value the state can notice, rather than a mutation nobody sees.
		var raw:Dynamic = entry.state.peek();
		var items:Array<Dynamic> = [];
		if (raw != null) {
			if (Std.isOfType(raw, Array)) items = raw;
			else for (item in (raw : Iterable<Dynamic>)) items.push(item);
		}

		var rows:Array<String> = [];
		for (item in items) {
			var view:View = Reflect.callMethod(null, entry.template, [item]);
			var text = firstText(view);
			var button = firstButton(view);

			var actionLabel = "";
			var actionId = -1;
			if (button != null) {
				actionLabel = Std.string(button.properties.get("label"));
				var cb = button.properties.get("onClick");
				var action = button.properties.get("action");
				if (Reflect.isFunction(cb)) {
					actionId = Callbacks.registerRow(cb);
				} else if (action != null) {
					actionId = Callbacks.registerRow(function() Actions.run(action));
				}
			}

			rows.push(text + FIELD + actionLabel + FIELD + actionId);
		}

		pushList(entry.stateName, rows.join(RECORD));
	}

	// Separators chosen because no label can contain them: ASCII 30 and 31 exist
	// for exactly this, which saves writing a JSON parser on the C++ side.
	static inline var RECORD = "\x1e";
	static inline var FIELD = "\x1f";

	/** First `Text` in a row, depth-first. Empty when the row has none. **/
	static function firstText(view:View):String {
		if (view == null) return "";
		if (view.viewType == "TextBlock" || view.viewType == "Text") {
			var t = view.properties.get("text");
			if (t != null) return Std.string(t);
		}
		for (child in view.children) {
			var found = firstText(child);
			if (found != "") return found;
		}
		return "";
	}

	/** First `Button` in a row, depth-first. **/
	static function firstButton(view:View):View {
		if (view == null) return null;
		if (view.viewType == "Button") return view;
		for (child in view.children) {
			var found = firstButton(child);
			if (found != null) return found;
		}
		return null;
	}

	/** Hand the rows to the generated C++, which owns the ListView. **/
	static function pushList(name:String, payload:String):Void {
		#if cpp
		untyped __cpp__("wui_bridge_push_list({0}.utf8_str(), {1}.utf8_str())", name, payload);
		#end
	}

	/**
		Make every `@:state` field push its writes to the generated C++.

		Constructing the app filled `wui.state.State`'s registry, so the fields
		are already there to be found — no macro-generated glue needed to name
		them. Each one gets a subscriber that forwards to the native handler, and
		since `wui.state.State` already routes its platform sink through that
		subscriber list, a plain `count.value = 3` reaches the UI.

		**Only `Int` travels today.** The other types are reported rather than
		skipped in silence: a state that quietly stops updating the UI is the
		failure this whole increment exists to make impossible.
	**/
	static function bindStates():Int {
		var bound = 0;

		for (name in wui.state.State._registry.keys()) {
			var st:Dynamic = wui.state.State._registry.get(name);
			if (st == null) continue;

			var current:Dynamic = st.peek();
			if (Std.isOfType(current, Int)) {
				st.subscribe(function(v:Dynamic) {
					pushInt(name, cast(v, Int));
				});
				bound++;
			} else if (Std.isOfType(current, String)) {
				st.subscribe(function(v:Dynamic) {
					pushString(name, v == null ? "" : Std.string(v));
				});
				bound++;
			} else {
				// A collection is not pushed as a value: a ListView bound to one
				// is rebuilt by `bindLists`. Anything else is a real gap.
				if (!isCollection(current)) {
					trace('[wui] state "$name": ${Type.typeof(current)} does not reach the UI yet, not pushing');
				}
			}
		}

		return bound;
	}

	/**
		Mount the app's node tree through the push contract.

		Called once, from `BuildUI`, after the root panel exists — the ordering
		lesson from W5b, where a list pushed before its control existed went
		nowhere. The app supplies its tree through `nuiBody()`.
	**/
	static var _pumpBroken = false;

	/** Called from the host's 100ms tick, and at once when work is queued
		(`watchMainEvents`) — see `wui_bridge_pump` above. The
		same defect on its fifth backend: a `haxe.Timer` registers with the
		current thread's event loop, and nobody advanced it. Guards and says it
		once if the thread has no loop at all. **/
	static var _watching = false;

	/**
		Wake the host whenever work is queued for this thread, from any thread.

		The 100 ms beat alone meant that a frame arriving off a socket waited
		for the next beat before anything drew it: the Farceur session measured
		a panel receiving 60 trees a second showing about ten, 55 ms late on
		average. `dui.socket.Pump` and `cafos.client.Marshal` both queue onto
		this thread's `sys.thread.EventLoop`, and its `wait()` returns every time
		something is queued — `run`, `repeat` and `runPromised` each release it.
		So one thread waits there and asks the host for a visit each time. It
		consumes wake-ups nobody else uses: this thread only ever calls
		`progress()`.

		Called on the UI thread, once the host has installed its requester. The
		beat stays, for timers that come due without anything being queued.
	**/
	@:keep public static function watchMainEvents():Void {
		if (_watching)
			return;
		// hxcpp only: the request crosses into the C++ this class is compiled
		// with. The host that installs a requester is always that build.
		#if (cpp && !cppia)
		var events:Null<sys.thread.EventLoop> = try sys.thread.Thread.current().events catch (_:Dynamic) null;
		if (events == null)
			return;
		_watching = true;
		final loop:sys.thread.EventLoop = events;
		sys.thread.Thread.create(() -> {
			while (true) {
				loop.wait();
				untyped __cpp__("wui_bridge_request_pump()");
			}
		});
		#end
	}

	@:keep public static function pumpHaxeEvents():Void {
		if (_pumpBroken) return;
		try {
			#if (target.threaded && !cppia)
			sys.thread.Thread.current().events.progress();
			#end
		} catch (e:Dynamic) {
			_pumpBroken = true;
			trace("[wui] no Haxe event loop on this thread; haxe.Timer will not fire: " + e);
		}
	}

	public static function renderNui(rootHandle:Int):Void {
		// Once. OnLaunched can be raised again (relaunch, activation), and the
		// boot is guarded but this was not: a second pass would have registered
		// a second root and mounted a second Primary over the first.
		if (primary != null) {
			trace("[wui] renderNui: the Primary surface is already mounted");
			return;
		}

		if (appInstance == null) {
			trace("[wui] renderNui: no app instance; install() has not run");
			return;
		}

		var node:nui.Node = null;
		try {
			node = appInstance.nuiBody();
		} catch (e:Dynamic) {
			trace('[wui] renderNui: the app has no nuiBody() ($e)');
			return;
		}

		if (node == null) {
			trace("[wui] renderNui: nuiBody() returned null");
			return;
		}

		// The per-surface record: its own sink and reconciler (instances
		// already), the root handle BuildUI registered, and -- for Primary --
		// the APPLICATION lifetime, because its passes bracket body(), which
		// is where the app's `keep` keys are declared. A later surface brings
		// a fresh Lifetime instead, so its sweep cannot touch these keys.
		var sink = new wui.nui.WinUISink();
		var record = new wui.nui.SurfaceRecord(rootHandle, sink,
			new wui.nui.Reconciler(sink), appInstance.lifetime);
		primary = record;

		// Render inside an effect, so the app never asks for a re-render.
		//
		// Anything reactive the view reads subscribes it, and a write to that
		// state reconciles on its own. Without this an app had to call
		// `rerenderNui()` by hand -- framework plumbing in application code, and
		// on a backend it is not supposed to name.
		record.effect = new rui.Signal.Effect(function() {
			record.lifetime.beginPass();
			var tree = appInstance.nuiBody();
			if (tree == null) {
				trace("[wui] nuiBody() returned null");
				return;
			}
			record.tree = record.reconciler.reconcile(record.tree, tree, record.root);
			// After reconcile, not after nuiBody(): a node with deferred
			// children has its thunk run in there, so that is where a component
			// has finished declaring.
			record.lifetime.endPass();
		});

		trace('[wui] nui: tree mounted on root ${record.root}, ${Callbacks.nodeCount()} handler(s)');

		// The Primary exists; now the windows the app declared. After, not
		// before: an auxiliary reading the same state as the body should find
		// the world the body already built.
		mountAuxiliaries();
	}

	/**
		The mui layer's hook for the app's Auxiliary declarations.

		This class is wui core and may not import `mui` — the surface
		vocabulary lives there. `wui.mui.App`'s constructor installs a provider
		that answers each `Tree(Auxiliary, …)` declaration as a node thunk (the
		conversion from views to nodes is the mui layer's business too, which
		is why the shape here is `nui.Node` and not a view: the push path eats
		nodes, and core stays free of both `mui` and its converter). A plain
		`wui.App` installs nothing and keeps exactly one window.
	**/
	public static var auxiliaryRootsOf:Dynamic -> Array<{id:String, node:() -> nui.Node}> = null;

	/**
		The injectable seam over window creation: the one native act in the
		auxiliary path a test cannot perform. Left null, creation crosses to
		the generated project through the `wui_bridge_create_window` slot; a
		test installs a counting function and the native side is never asked.
	**/
	public static var windowCreator:String -> Int = null;

	static function createWindow(title:String):Int {
		if (windowCreator != null) return windowCreator(title);
		#if cpp
		var handle:Int = -1;
		untyped __cpp__("{0} = wui_bridge_create_window({1}.utf8_str())", handle, title);
		return handle;
		#else
		return -1;
		#end
	}

	/** Auxiliary records by their root handle — the key the Closed handler
		reports back. Cardinality Many: every declaration gets a window. **/
	static var auxiliaries:Map<Int, wui.nui.SurfaceRecord> = new Map();

	static function mountAuxiliaries():Void {
		if (auxiliaryRootsOf == null) return;

		for (decl in auxiliaryRootsOf(appInstance)) {
			var handle = createWindow(windowTitle(decl.id));
			if (handle < 0) {
				trace('[wui] auxiliary "${decl.id}": no window creator registered, not mounted');
				continue;
			}

			// The per-surface record again -- with its OWN lifetime this time.
			// The Primary carries the application's, because its passes bracket
			// body(); an auxiliary's passes bracket its own content, and a
			// shared lifetime would sweep the app's keep keys on this surface's
			// schedule.
			var sink = new wui.nui.WinUISink();
			var record = new wui.nui.SurfaceRecord(handle, sink,
				new wui.nui.Reconciler(sink), new rui.Lifetime());
			auxiliaries.set(handle, record);

			var node = decl.node;
			record.effect = new rui.Signal.Effect(function() {
				record.lifetime.beginPass();
				var tree = node();
				if (tree == null) {
					trace('[wui] auxiliary "${decl.id}": the declaration returned null');
					return;
				}
				record.tree = record.reconciler.reconcile(record.tree, tree, record.root);
				record.lifetime.endPass();
			});

			trace('[wui] auxiliary "${decl.id}" mounted on root $handle');
		}
	}

	/**
		An auxiliary window was closed. Dispose exactly that record — its
		effect and its own lifetime — and nothing else: the not-wiping is the
		whole point of the partition. Unknown handles are ignored, which also
		makes a second Closed report a no-op (dispose overlaps with release by
		contract, and both may arrive).
	**/
	public static function surfaceClosed(rootHandle:Int):Void {
		var record = auxiliaries.get(rootHandle);
		if (record == null) return;
		auxiliaries.remove(rootHandle);
		record.dispose();
	}

	/** One auxiliary's record, by root handle. For tools and tests; an
		application has no business holding these. **/
	public static function auxiliaryRecord(rootHandle:Int):Null<wui.nui.SurfaceRecord> {
		return auxiliaries.get(rootHandle);
	}

	/** "inspector" -> "Inspector": the declaration id is code-shaped, the
		title bar is not. One capital, nothing cleverer -- an app that cares
		about its auxiliary titles will grow a property for it. **/
	static function windowTitle(id:String):String {
		if (id == null || id.length == 0) return "Window";
		return id.charAt(0).toUpperCase() + id.substr(1);
	}

	/**
		Tear every surface down: the auxiliaries first — each releases its own
		lifetime — then the Primary, whose lifetime is the application's, so
		everything the app `own()`ed goes last. Idempotent, because a window
		Closed handler and a process exit overlap. The native controls die with
		their windows; their handles become permanent holes. (The name kept its
		Primary-era spelling: the ABI list for the Windows pass already carries
		`wui_bridge_dispose_primary`, and what it means is "the application is
		over".)
	**/
	public static function disposePrimary():Void {
		// Snapshot the keys: surfaceClosed removes as it goes, and mutating a
		// map mid-iteration is exactly the kind of works-on-one-target bug
		// this backend has paid for before.
		for (handle in [for (h in auxiliaries.keys()) h]) surfaceClosed(handle);
		if (primary == null) return;
		primary.dispose();
		primary = null;
	}

	/**
		Force a re-render.

		Rarely needed: `renderNui` runs the view inside an effect, so reactive
		state re-renders on its own. This stays for a view that depends on
		something outside the reactive system.

		This is the whole point of the push contract: the app asks for a fresh
		tree, and the controls that did not change are never touched — so a text
		box keeps its text, its caret and its selection while the list around it
		is reordered.
	**/
	public static function rerenderNui():Void {
		if (primary == null || appInstance == null) {
			trace("[wui] rerenderNui: nothing mounted yet");
			return;
		}

		var node:nui.Node = appInstance.nuiBody();
		if (node == null) {
			trace("[wui] rerenderNui: nuiBody() returned null");
			return;
		}

		primary.tree = primary.reconciler.reconcile(primary.tree, node, primary.root);
	}

	/** The Primary surface's record -- what used to be four statics. A later
		surface (an Auxiliary window) gets its own record, not a fifth static. **/
	static var primary:Null<wui.nui.SurfaceRecord> = null;

	/** Arrays and the persistent structures a list state is meant to hold. **/
	static function isCollection(v:Dynamic):Bool {
		if (v == null) return false;
		if (Std.isOfType(v, Array)) return true;
		return Std.isOfType(v, rui.structures.ImmutableList);
	}

	/** Hand one integer to the generated C++, which owns `s_<name>`. **/
	static function pushInt(name:String, value:Int):Void {
		#if cpp
		untyped __cpp__("wui_bridge_push_int({0}.utf8_str(), {1})", name, value);
		#end
	}

	/** Same, for text. UTF-8 both ways; the C++ side widens. **/
	static function pushString(name:String, value:String):Void {
		#if cpp
		untyped __cpp__("wui_bridge_push_string({0}.utf8_str(), {1}.utf8_str())", name, value);
		#end
	}

	/**
		Record a change the platform made, without pushing it back.

		Called when the user edits a `TextBox`. `applyExternal` runs the effects
		and **skips the platform sink**, so the value does not travel back to the
		control it just came from — which on every keystroke would rewrite the text
		mid-edit and move the caret.
	**/
	public static function applyExternalString(name:String, value:String):Void {
		var st:Dynamic = wui.state.State.getByName(name);
		if (st == null) {
			trace('[wui] external change for unknown state "$name"');
			return;
		}
		st.applyExternal(value);
	}

	/**
		Depth-first over `children`, registering each button that carries a Haxe
		closure.

		**The order is the contract.** The generator numbers the same tree with
		the same walk, so anything that changes this traversal changes which
		closure a click runs — see `Callbacks`.
	**/
	static function collect(view:View):Void {
		if (view == null) return;

		if (view.viewType == "Button") {
			// Exactly one registration per button that has an action, in either
			// form, because the generator numbers buttons the same way. A button
			// carrying both takes the closure: it is the more specific of the two.
			var cb = view.properties.get("onClick");
			var action = view.properties.get("action");

			if (Reflect.isFunction(cb)) {
				Callbacks.register(cb);
			} else if (action != null) {
				Callbacks.register(function() Actions.run(action));
			}
		}

		for (child in view.children) collect(child);
	}

	/** Is the native side up? False when the library was not linked. **/
	public static function isReady():Bool {
		#if cpp
		var ready:Bool = false;
		untyped __cpp__("{0} = wui_bridge_ready()", ready);
		return ready;
		#else
		return false;
		#end
	}
}
